### ISSUE TITLE
Spelling mistake: retrivableValue should be retrievableValue

### ISSUE THREAD

**Issue by mitchwd** [KarimEbrahemAbdelaziz/SwiftyMenu#17]
In SwiftMenuDisplayable.swift,
Line 33, `var retrivableValue: Any { get }`
should be `var retrievableValue: Any { get }`

Documentation and other references will also need to be updated.

**Comment by KarimEbrahemAbdelaziz** [comment]
Thank you @mitchwd  <3
I will fix this spelling mistake this week :)
