### ISSUE TITLE
SnapKit dependency is outdated

### ISSUE THREAD

**Issue by mitchwd** [KarimEbrahemAbdelaziz/SwiftyMenu#18]
Please update the SnapKit dependency to use a more up to date version of SnapKit. 
The currently used version is 4.2.0, released in October 2018.
The latest version is 5.0.1, released in August 2019. This version also migrates to using Swift 5.

https://github.com/SnapKit/SnapKit/tags

**Comment by KarimEbrahemAbdelaziz** [comment]
@mitchwd Thank you for notify me. Will update it very soon :)

**Comment by mitchwd** [comment]
Thanks @KarimEbrahemAbdelaziz!
