### ISSUE TITLE
setting the current selectedIndex programmatically doesn't show the selecteditem

### ISSUE THREAD

**Issue by aviya-smila** [KarimEbrahemAbdelaziz/SwiftyMenu#21]
Hi,
I'm facing an issue when setting the current selectedIndex programmatically doesn't show the selected item.
when trying to debug I noticed that the button does'nt include any uilabel.

**Comment by jordanjanaq** [comment]
I did in the on viewDidAppear and it works. Maybe the view is not setting the selection when it's created.

**Comment by KarimEbrahemAbdelaziz** [comment]
Hi @aviya-smila ,

Just as @jordanjanaq said, you need to set it in `viewDidAppear` as I didn't set the selection while creating the view.

Thank you :)
