### ISSUE TITLE
Cannot assign value of type '[String]' to type '[SwiftyMenuDisplayable]'

### ISSUE THREAD

**Issue by PacoPacoPakitor** [KarimEbrahemAbdelaziz/SwiftyMenu#26]
hi, when i tried the code as pic, but it's not work for me. can you help me?

![image](https://user-images.githubusercontent.com/23376484/110664476-0031c180-81fa-11eb-9e19-a9610cb784d1.png)
![image](https://user-images.githubusercontent.com/23376484/110664587-1dff2680-81fa-11eb-9b42-339cab22bf4f.png)

**Comment by rursache** [comment]
add this extension to your project

```
extension String: SwiftyMenuDisplayable {
    public var displayableValue: String {
        return self
    }
    
    public var retrievableValue: Any {
        return self
    }
}
```

**Comment by KarimEbrahemAbdelaziz** [comment]
@PacoPacoPakitor as @rursache mentioned in the comment.
You have to make whatever type you want to add to `SwiftyMeny` conform to `SwiftyMenuDisplayable`.
Thank you
