### ISSUE TITLE
Error with latest version when installing with SPM

### ISSUE THREAD

**Issue by palla89** [KarimEbrahemAbdelaziz/SwiftyMenu#29]
Hi! I tried installing with SPM but I got lot of errors, installation with Cocoapods went fine and smooth instead.
`Cannot find type 'UIColor' in scope
Cannot find type 'UIFont' in scope` and such

<img width="694" alt="Schermata 2021-10-05 alle 10 36 11" src="https://user-images.githubusercontent.com/12301205/135989412-a39125ce-dfb8-4ac8-a06a-9371b7b27050.png">

**Comment by KarimEbrahemAbdelaziz** [comment]
Solved ✅ 
Thanks to @blerdfoniqi :)
