### ISSUE TITLE
wrong margin for arrow's position in RTL layout

### ISSUE THREAD

**Issue by amrangry** [KarimEbrahemAbdelaziz/SwiftyMenu#3]
when switching from LTR  to RTL 
the position of the arrow has no space "margin" to the left edge of the view

**Comment by KarimEbrahemAbdelaziz** [comment]
Thanks for mention RTL issue, Amr.
I will work on it ASAP, and if you fixed it please make PR. :)

**Comment by BHZiva** [comment]
@KarimEbrahemAbdelaziz even in normal layout how to deal with margins of arrow ? I want to add some right inset to image but seems nothing working. Please help.

**Comment by KarimEbrahemAbdelaziz** [comment]
Fixed @amrangry @BHZiva thank you :)
