### ISSUE TITLE
It seems like There is a problem with the SPM Installation

### ISSUE THREAD

**Issue by DCherish** [KarimEbrahemAbdelaziz/SwiftyMenu#38]
Hi :) First of all, thank you for creating a GREAT library.

Anyway, I tried to install SwiftyMenu(version 1.0.1) on the project using SPM.

But the files before the modification were installed in the app, so it seems that the same error still occurs.
(Image #1 ; In this SwiftyMenu File)
<img width="892" alt="스크린샷 2023-03-26 11 55 58" src="https://user-images.githubusercontent.com/68846212/227752820-e7e41de6-deb6-4b85-a2a7-bf03e291948d.png">
(Image #2-1 ; Actually included file(Package.swift) in the project)
<img width="955" alt="스크린샷 2023-03-26 11 58 15" src="https://user-images.githubusercontent.com/68846212/227752942-bebe7ad2-eb29-4bf3-8b41-b6146513b80a.png">
(Image #2-2 ; Actually included file() in the project)
<img width="1134" alt="스크린샷 2023-03-26 11 58 26" src="https://user-images.githubusercontent.com/68846212/227752946-6b8fdbb9-433d-4cde-b12a-67c6715ee958.png">
(Image #3 ; Error occurs like #37 )
<img width="569" alt="스크린샷 2023-03-26 11 58 35" src="https://user-images.githubusercontent.com/68846212/227752999-2d0988ed-0bfa-45bc-a27b-18ec6cfef241.png">

Could you please check if there is any problem?

Thanks :)

**Comment by KarimEbrahemAbdelaziz** [comment]
Hello @DCherish ,

This issue should be solved now after this [PR](https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu/pull/37).

Thanks for reporting :)
