### ISSUE TITLE
Cannot assign value of type '[String]' to type '[SwiftMenuDisplayable]'

### ISSUE THREAD

**Issue by RimsonLiu** [KarimEbrahemAbdelaziz/SwiftyMenu#4]
```
let data = ["option1", "option2"]
let menu = SwiftyMenu()
mune.options = data
```
When I write like this, Xcode give me an error:
`Cannot assign value of type '[String]' to type '[SwiftMenuDisplayable]'`

**Comment by KarimEbrahemAbdelaziz** [comment]
Could you please check the example project?! 
The types used in SwiftyMenu should conform to SwiftMenuDisplayable to protocol.
So in your example you should do extension for String to conform to that protocol.

**Comment by RimsonLiu** [comment]
Thanks, my bad.

**Comment by RimsonLiu** [comment]
I need to do extension for String to conform to that protocol.
