### ISSUE TITLE
a crash when using with SPM for the default arrow image 

### ISSUE THREAD

**Issue by amrangry** [KarimEbrahemAbdelaziz/SwiftyMenu#41]
While using SPM

the following error is appearing

![Screen Shot 2023-05-15 at 11 35 39 AM](https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu/assets/2900952/86f27106-a099-4d48-a566-ddc41577ed49)

**Comment by KarimEbrahemAbdelaziz** [comment]
Should be fixed now with this [PR](https://github.com/KarimEbrahemAbdelaziz/SwiftyMenu/pull/37). Thanks @amrangry for reporting this :)
