### ISSUE TITLE
Swifty Menu not working for transparent row background color 

### ISSUE THREAD

**Issue by iris112** [KarimEbrahemAbdelaziz/SwiftyMenu#5]
Hi.
I'm going to implement transparent swiftymenu for row items.
But currently only keep white color.

Could you please help me how can I solve this problem?

Thanks.
Regards.

**Comment by KarimEbrahemAbdelaziz** [comment]
Hey Iris, 

Do you need to rows to be with transparent background?!

**Comment by iris112** [comment]
Hi.
I' solved this problem.
Thanks.
