### ISSUE TITLE
SwiftyMenu from code

### ISSUE THREAD

**Issue by quantime-projects** [KarimEbrahemAbdelaziz/SwiftyMenu#6]
There a example how to add SwiftyMenu from code without storyboard?

**Comment by KarimEbrahemAbdelaziz** [comment]
I will add this example today and notify you :) 
Thanks

**Comment by quantime-projects** [comment]
Thanks

**Comment by KarimEbrahemAbdelaziz** [comment]
I tried to update the example today, but it seems SwiftyMenu don't support implementation from code now.
I will let this in my progress as a new feature.
You contribution is also more than welcome 👍:)

**Comment by quantime-projects** [comment]
I will be trying to implement it and see how I can contribute.

**Comment by KarimEbrahemAbdelaziz** [comment]
It will be nice from you :)
and if not don't worry, it will be on my list to do it ASAP.
Thanks Again .. ☺️

**Comment by KarimEbrahemAbdelaziz** [comment]
Hello @quantime-projects ,

Using `SwiftyMenu` programmatically will be available in next release 0.6.0 🔥
