### ISSUE TITLE
Option to Expand/Collapse menu from code

### ISSUE THREAD

**Issue by masterpaulo** [KarimEbrahemAbdelaziz/SwiftyMenu#7]
Hi, is there by any chance a way to manually trigger expanding/collapsing the menu? As I see from the code, the methods to achieve this are set to private... or is there a specific interface for this? Thanks

**Comment by KarimEbrahemAbdelaziz** [comment]
Hey @masterpaulo 
Actually no, you can't do it now with existing implementation.
But we can do it public or provide and interface to do it :)

**Comment by bogdan-razvan** [comment]
That would be a feature worth implementing. 👍

**Comment by leiwang423** [comment]
I need collapsing the menu when user touch other part in the screen.  A public interface will be great.

**Comment by BHZiva** [comment]
@bogdan-razvan @leiwang423 @amrangry I tried using dropDownMenu.hideOptionsWhenSelect = true and its working for me.

**Comment by KarimEbrahemAbdelaziz** [comment]
> That would be a feature worth implementing. 👍

> I need collapsing the menu when user touch other part in the screen. A public interface will be great.

> @bogdan-razvan @leiwang423 @amrangry I tried using dropDownMenu.hideOptionsWhenSelect = true and its working for me.

It's currently under very active development and will be available in 0.6.0 version 🔥💪🏻

**Comment by KarimEbrahemAbdelaziz** [comment]
Already added and will be available in next release 👍

**Comment by BHZiva** [comment]
Hello,

When will be the next release?

Thanks,
Bhargavi

**Comment by KarimEbrahemAbdelaziz** [comment]
Hey BHZiva,

SwiftyMenu updated and it's now 0.6.1 , please update your version to have the new feature and please check Releases page for more information 😊

Thank you.

**Comment by BHZiva** [comment]
Hi Karim,

Thanks for quick response. It's noted.

Thanks,
Bhargavi

**Comment by BHZiva** [comment]
Hi KarimEbrahemAbdelaziz/SwiftyMenu,

CAN THIS MENU DISPLAY LAZY LOADED IMAGE FROM PATH ? LIKE IMAGES ?


Thanks,
Bhargavi

**Comment by KarimEbrahemAbdelaziz** [comment]
Hey @BHZiva ,

I can't get what are you trying to say actually 😅
Could you please explain it more ?

What I got is, you need to select images rather than options ?!

**Comment by BHZiva** [comment]
Hello,

I wanted to say right now we have string datatypes for options. are we
allowed to load images ? Is there any provision for loading images from
server as options ?

Thanks,
Bhargavi

**Comment by KarimEbrahemAbdelaziz** [comment]
Hey @BHZiva ,

Currently you can't. 
But It will be added to customization I'm working on nowadays. So wait it :)

Thank you.

**Comment by BHZiva** [comment]
alright thanks

Thanks,
Bhargavi

**Comment by NasrullahKhan** [comment]
Hi.. currently is used this dropDownMenu.hideOptionsWhenSelect = true but facing issue.

when the dropdown collapses with hideOptionsWhenSelect and tap again on dropdown doesn't work because it's giving callback didCollapse twice.

**Comment by KarimEbrahemAbdelaziz** [comment]
Hello @NasrullahKhan 
Oki, I'll check this issue today and try to fix it :)
Could you please give me full scenario please ?
