### ISSUE TITLE
String array not accepting as optiondata

### ISSUE THREAD

**Issue by Jaydip-iOS** [KarimEbrahemAbdelaziz/SwiftyMenu#8]
dropdownMenu.options = ["Test1,"test2"] 

**Error** : Cannot assign value of type '[String]' to type '[SwiftyMenuDisplayable]'

**Comment by KarimEbrahemAbdelaziz** [comment]
Hey Jaydip,
You need to confirm to `SwiftyMenuDisplayable ` for the type you need to support in your menu.
Let me know if you face any other problem :)

**Comment by GMRemie** [comment]
Yeah, I had this problem last night was going to reply. I just made an extension to the String that implemented the `SwiftyMenuDisplayable` protocol, worked fine.
