### ISSUE TITLE
How to disable inputAccessoryView and how to inset arrow image ?

### ISSUE THREAD

**Issue by Bhargavi-Enrich** [KarimEbrahemAbdelaziz/SwiftyMenu#9]
Hi I want to achieve below.

1) Disable input accessory view.
2) adding inset/padding/margin for arrow image.

Please suggest me what can I use for this.
I already tried couple of things with provided properties.

**Comment by KarimEbrahemAbdelaziz** [comment]
Hello @BHZiva ,
Sure I help you achieve your points :) 

1. Which input accessory view do you mean ?

2. I am currently working on adding more customization to the SwiftyMenu appearance, one of them is the arrow image. So wait this update very soon ☺️

**Comment by BHZiva** [comment]
Hi,

1) by accessory view I mean right tick coming beside selected row in
dropdown. I want to hide selection tick.
2) For arrows image, there is padding issues. It's aligned so right to
control. It's not manageable with current version.

Thanks,
Bhargavi

**Comment by KarimEbrahemAbdelaziz** [comment]
@BHZiva I am currently working on Customizations as I mentioned in last reply and will take your points into consideration ☺️
Thanks for your feedback ❤️

**Comment by KarimEbrahemAbdelaziz** [comment]
The coming version will provide attribute to disable the selection accessory view. And I fixed the padding issue in the coming version also. 
Thank you @Bhargavi-Enrich :)
